### ISSUE TITLE
Headless tests don't work in OpenJDK

### ISSUE THREAD

**Issue by AdamCarroll** [VocabHunter/VocabHunter#13]
Running the headless GUI tests in the OpenJDK produces the following error that doesn't occur with the Oracle JDK:

```
io.github.vocabhunter.gui.main.GuiTest > classMethod FAILED
    java.lang.RuntimeException: java.lang.RuntimeException: java.lang.AbstractMethodError: com.sun.glass.ui.monocle.NativePlatform.createInputDeviceRegistry()Lcom/sun/glass/ui/monocle/InputDeviceRegistry;
        at org.testfx.util.WaitForAsyncUtils.waitFor(WaitForAsyncUtils.java:161)
        at org.testfx.api.FxToolkit.waitForLaunch(FxToolkit.java:264)
        at org.testfx.api.FxToolkit.registerPrimaryStage(FxToolkit.java:126)
        at io.github.vocabhunter.gui.main.GuiTest.setupSpec(GuiTest.java:90)

        Caused by:
        java.lang.RuntimeException: java.lang.AbstractMethodError: com.sun.glass.ui.monocle.NativePlatform.createInputDeviceRegistry()Lcom/sun/glass/ui/monocle/InputDeviceRegistry;

            Caused by:
            java.lang.AbstractMethodError: com.sun.glass.ui.monocle.NativePlatform.createInputDeviceRegistry()Lcom/sun/glass/ui/monocle/InputDeviceRegistry;
```

This was tested on Ubuntu 16.04 with OpenJDK v1.8.0_91.

**Comment by AdamCarroll** [comment]
This problem is now resolved in OpenJDK v1.8.0_151.
