### ISSUE TITLE
Upgrading to JavaFX v15.0.1 causes the headless GUI test to fail

### ISSUE THREAD

**Issue by AdamCarroll** [VocabHunter/VocabHunter#51]
If I change the JavaFX version in JavaFX plugin from v13.0.2 to v15.0.1, the headless GUI test fails:

```
$ ./gradlew :gui:test --tests io.github.vocabhunter.gui.main.GuiTest --info
...
    INFO  STEP 9: Begin - Write note and add to word
    INFO  STEP 9:   End - Write note and add to word
    INFO  STEP 10: Begin - Open note with keyboard

Gradle Test Executor 53 finished executing tests.

> Task :gui:test FAILED

GuiTest > testWalkThrough(FxRobot) FAILED
    org.testfx.service.query.EmptyNodeQueryException: there is no node in the scene-graph matching the query: NodeQuery: from nodes: [BorderPane@389a5b93[styleClass=root]],
    lookup by function: "org.testfx.util.NodeQueryUtils$$Lambda$679/0x0000000800631840@6203ffa1",
    lookup by selector: "#textAreaNoteText"
        at org.testfx.service.query.impl.NodeQueryImpl.query(NodeQueryImpl.java:132)
        at org.testfx.api.FxAssert.toNode(FxAssert.java:168)
        at org.testfx.api.FxAssert.verifyThat(FxAssert.java:71)
        at io.github.vocabhunter.gui.main.GuiTestSteps.lambda$part2BasicWalkThrough$9(GuiTestSteps.java:107)
        at io.github.vocabhunter.gui.main.GuiTestSteps.step(GuiTestSteps.java:385)
        at io.github.vocabhunter.gui.main.GuiTestSteps.part2BasicWalkThrough(GuiTestSteps.java:105)
        at io.github.vocabhunter.gui.main.GuiTest.testWalkThrough(GuiTest.java:160)

1 test completed, 1 failed
...
BUILD FAILED in 20s
10 actionable tasks: 2 executed, 8 up-to-date
```

**Comment by AdamCarroll** [comment]
I just tested with the new JavaFX v16 and can still see the same problem
